### ISSUE TITLE
In IOS 9.3.1 arm 64 error?

### ISSUE THREAD

**Issue by bintu1234** [mtonio91/AMSmoothAlert#36]
HI I am working with This Lib. before this it is working fine. Now i am facing one issue regarding versions. I just update my iphone to 9.3.1 when i debug i am getting below error 
`Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_GPUImageiOSBlurFilter", referenced from:
      objc-class-ref in AMSmoothAlertView.o
ld: symbol(s) not found for architecture arm64
`
It is working fine in Ios 9.2
How to resolve This please help me.
